# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3b2fc116a9b667a9d58147432b505c90636c637a29620b2f2ff8f2eef9fc95750a7ef85d5d51cc9a67c143625c8e39df4141596a679fcd65f92c6198e42ce2

test:
  secret_key_base: a6ff3699d2bb53b07ae663bc15e79f4215ac358632d70eb422cf450e76ad515e0c8c4b04755e5b23bd01018b7ed5aeb6a23948a97fa193201c59cf3898426d7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
